name: Check, Build and Artifact Deploy
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # https://github.com/actions/setup-java/issues/298

      - name: Install Packages
        working-directory: src/frontend
        run: |
          npm install

      - name: Lint check
        working-directory: src/frontend
        run: |
          npm run lint

      - name: Test check
        working-directory: src/frontend
        run: |
          npm run test

      - name: Build
        working-directory: src/frontend
        run: |
          npm run build

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0

      - name: Build with Gradle
        run: ./gradlew clean publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}